version: '3.8'

services:
  admin-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
      - "3000:3000"  # Frontend dev server
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/backend-sample/.gradle
      - /app/frontend-generator/node_modules
      - /app/generated-frontend/node_modules
    restart: unless-stopped
    working_dir: /app